### ISSUE TITLE
Win32 Error

### ISSUE THREAD

**Issue by mitchgw1** [SJ001/AI-Feynman#5]
Hi Silviu,

Thanks, for sharing your code. It looks like you guys have been doing some awesome work.

I've been getting the following error when I run ai_feynman_example.py. Have you ever encountered this issue before/do you have any idea what might be going wrong?

Thanks a lot,
Mitch

Error Message:
C:\Users\mitch\anaconda3\python.exe "E:/Documents/Aaaaa School Stuff/NSTRF/Modeling/AI-Feynman-master/Code/ai_feynman_example.py"
Checking for brute force + 

Traceback (most recent call last):
  File "E:/Documents/Aaaaa School Stuff/NSTRF/Modeling/AI-Feynman-master/Code/ai_feynman_example.py", line 3, in <module>
    run_aifeynman("../example_data/","example2.txt",30,"14ops.txt", polyfit_deg=4, NN_epochs=400)
  File "E:\Documents\Aaaaa School Stuff\NSTRF\Modeling\AI-Feynman-master\Code\S_run_aifeynman.py", line 165, in run_aifeynman
    PA = run_AI_all(pathdir,filename+"_train",BF_try_time,BF_ops_file_type, polyfit_deg, NN_epochs)
  File "E:\Documents\Aaaaa School Stuff\NSTRF\Modeling\AI-Feynman-master\Code\S_run_aifeynman.py", line 39, in run_AI_all
    PA = run_bf_polyfit(pathdir,pathdir,filename,BF_try_time,BF_ops_file_type, PA, polyfit_deg)
  File "E:\Documents\Aaaaa School Stuff\NSTRF\Modeling\AI-Feynman-master\Code\S_run_bf_polyfit.py", line 27, in run_bf_polyfit
    brute_force(pathdir_transformed,filename,BF_try_time,BF_ops_file_type,"+")
  File "E:\Documents\Aaaaa School Stuff\NSTRF\Modeling\AI-Feynman-master\Code\S_brute_force.py", line 27, in brute_force
    subprocess.call(["./brute_force_oneFile_v3.scr", file_type, "%s" %try_time, pathdir+filename])
  File "C:\Users\mitch\anaconda3\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\mitch\anaconda3\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\mitch\anaconda3\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application

Process finished with exit code 1

**Comment by rui0511** [comment]
Hi Silviu,

I have exactly the same problem too. My computer is Win 10 64-bit.

Rui
Best   

Error Message:
Checking for brute force + 

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-6-175d416004b5> in <module>
----> 1 run_aifeynman("../example_data/","example2.txt",30,"14ops.txt", polyfit_deg=4, NN_epochs=400)

F:\AI-Feynman-master\Code\S_run_aifeynman.py in run_aifeynman(pathdir, filename, BF_try_time, BF_ops_file_type, polyfit_deg, NN_epochs, vars_name, test_percentage)
    163     PA = ParetoSet()
    164     # Run the code on the train data
--> 165     PA = run_AI_all(pathdir,filename+"_train",BF_try_time,BF_ops_file_type, polyfit_deg, NN_epochs)
    166     PA_list = PA.get_pareto_points()
    167 

F:\AI-Feynman-master\Code\S_run_aifeynman.py in run_AI_all(pathdir, filename, BF_try_time, BF_ops_file_type, polyfit_deg, NN_epochs, PA)
     37 
     38     # Run bf and polyfit
---> 39     PA = run_bf_polyfit(pathdir,pathdir,filename,BF_try_time,BF_ops_file_type, PA, polyfit_deg)
     40 
     41     # Run bf and polyfit on modified output

F:\AI-Feynman-master\Code\S_run_bf_polyfit.py in run_bf_polyfit(pathdir, pathdir_transformed, filename, BF_try_time, BF_ops_file_type, PA, polyfit_deg, output_type)
     25     # run BF on the data (+)
     26     print("Checking for brute force + \n")
---> 27     brute_force(pathdir_transformed,filename,BF_try_time,BF_ops_file_type,"+")
     28 
     29     try:

F:\AI-Feynman-master\Code\S_brute_force.py in brute_force(pathdir, filename, BF_try_time, BF_ops_file_type, sep_type)
     27     if sep_type=="+":
     28         #subprocess.call(["./brute_force_oneFile_v3.scr", file_type, "%s" %try_time, pathdir+filename])
---> 29         subprocess.call(["./brute_force_oneFile_mdl_v2.scr", file_type, "%s" %try_time, pathdir+filename, "10", "0"])
     30     return 1
     31 

~\anaconda3\lib\subprocess.py in call(timeout, *popenargs, **kwargs)
    337     retcode = call(["ls", "-l"])
    338     """
--> 339     with Popen(*popenargs, **kwargs) as p:
    340         try:
    341             return p.wait(timeout=timeout)

~\anaconda3\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors, text)
    798                                 c2pread, c2pwrite,
    799                                 errread, errwrite,
--> 800                                 restore_signals, start_new_session)
    801         except:
    802             # Cleanup if the child failed starting.

~\anaconda3\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_start_new_session)
   1205                                          env,
   1206                                          os.fspath(cwd) if cwd is not None else None,
-> 1207                                          startupinfo)
   1208             finally:
   1209                 # Child is launched. Close the parent's copy of those pipe

OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by SJ001** [comment]
Dear Mitch and Rui,

Thank you for your interest in our code! We actually haven't tested the code on a Windows machine, so I am not totally sure about the possible errors that can appear there. Did you manage to run compile.sh successfully (e.g. did some .x files, resulted from fortran compilation appear)?

**Comment by mitchgw1** [comment]
Silviu,

Yeah I was able to run compile.sh. It produces a few "symbolic_regress" .x files.

**Comment by Betaglutamate** [comment]
I can confirm that this happens in window and on linux.

```
betaglutamate@LAPTOP-EOA26H9L:/mnt/d/ai_feynman/AI-Feynman/Code$ python3 ai_feynman_terminal_example.py --pat
hdir=../example_data/ --filename=example2.txt
Checking for brute force +

Traceback (most recent call last):
  File "ai_feynman_terminal_example.py", line 18, in <module>
    NN_epochs=opts.NN_epochs, vars_name=opts.vars_name, test_percentage=opts.test_percentage)
  File "/mnt/d/ai_feynman/AI-Feynman/Code/S_run_aifeynman.py", line 164, in run_aifeynman
    PA = run_AI_all(pathdir,filename+"_train",BF_try_time,BF_ops_file_type, polyfit_deg, NN_epochs, PA=PA)
  File "/mnt/d/ai_feynman/AI-Feynman/Code/S_run_aifeynman.py", line 38, in run_AI_all
    PA = run_bf_polyfit(pathdir,pathdir,filename,BF_try_time,BF_ops_file_type, PA, polyfit_deg)
  File "/mnt/d/ai_feynman/AI-Feynman/Code/S_run_bf_polyfit.py", line 27, in run_bf_polyfit
    brute_force(pathdir_transformed,filename,BF_try_time,BF_ops_file_type,"+")
  File "/mnt/d/ai_feynman/AI-Feynman/Code/S_brute_force.py", line 28, in brute_force
    subprocess.call(["./brute_force_oneFile_v3.scr", file_type, "%s" %try_time, pathdir+filename])
  File "/usr/lib/python3.6/subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './brute_force_oneFile_v3.scr': './brute_force_oneFile_v3.scr'
```

**Comment by mitchgw1** [comment]
Had the same issue, Betaglutamate. I was able to get it resolved though. I think you might be missing "csh". It's a command language interpreter. The Linux install command is: $ sudo apt-get install csh. Try rerunning after you get the new interpreter. 

Once I installed csh I was able to begin example code execution, but for some reason it never seems to finish (even after like 3 days). Trying to work that out now.

**Comment by Betaglutamate** [comment]
Thanks Mitch it works but I seem to have the same issue.

```
/mnt/d/ai_feynman/AI-Feynman/Code$ python3 ai_feynman_terminal_example.py --pathdir=../example_data/ --filename=example2.txt
Checking for brute force +

^M: Command not found.
^M: Command not found.
Trying to solve mysteries with brute force...
^M: Command not found.
...ing to solve ../example_data/example2.txt_train
 mystery.dat./example_data/example2.txt_train
/bin/cp: cannot stat '../example_data/example2.txt_train'$'\r': No such file or directory
^M: Command not found.
timeout: invalid time interval ‘60\rs’
Try 'timeout --help' for more information.
^M: Command not found.
Checking for brute force *

^M: Command not found.
^M: Command not found.
Trying to solve mysteries with brute force...
^M: Command not found.
...ing to solve ../example_data/example2.txt_train
 mystery.dat./example_data/example2.txt_train
/bin/cp: cannot stat '../example_data/example2.txt_train'$'\r': No such file or directory
timeout: invalid time interval ‘60\rs’
Try 'timeout --help' for more information.
Checking polyfit

Complexity  RMSE  Expression
[13.60964047443681, 31.770329997618862, 'x0*x1 + x0 - x1 + 1']
[59.21663995022191, 30.57115402958708, '0.535889014700659*x0*x1 + x0 - x1 + 1']
[249.31526647943755, 28.94369572341426, '0.535889014700659*x0*x1 + 0.741836183925367*x0 + 0.389356252208634*x1**2 - 0.215977654733002*x1*x2 - 0.681392290927942*x1 + 1']
[597.0755011637102, 27.466495540561752, '-0.125572595987532*x0*x1*x2 + 0.535889014700659*x0*x1 + 0.0136642220611202*x0*x2**2 + 0.741836183925367*x0 - 0.0600204937155282*x1**2*x2 + 0.389356252208634*x1**2 + 0.0770714313933922*x1*x2**2 - 0.215977654733002*x1*x2 - 0.681392290927942*x1 - 0.00978086237435278*x2**3 + 0.0357896164330423*x2**2 - 0.121674409409858*x2 + 0.886626511820445']
[636.6848037652464, 27.05335573865928, '-0.125572595987532*x0*x1*x2 + 0.535889014700659*x0*x1 + 0.0136642220611202*x0*x2**2 - 0.00838664365453991*x0*x2 + 0.741836183925367*x0 - 0.0600204937155282*x1**2*x2 + 0.389356252208634*x1**2 + 0.0770714313933922*x1*x2**2 - 0.215977654733002*x1*x2 - 0.681392290927942*x1 - 0.00978086237435278*x2**3 + 0.0357896164330423*x2**2 - 0.121674409409858*x2 + 0.886626511820445']
[795.0447340856714, 23.86627678145459, '0.00736029933290511*x0*x1*x2**2 - 0.125572595987532*x0*x1*x2 + 0.535889014700659*x0*x1 - 0.00104904665593723*x0*x2**3 + 0.0136642220611202*x0*x2**2 - 0.00838664365453991*x0*x2 + 0.741836183925367*x0 - 0.0600204937155282*x1**2*x2 + 0.389356252208634*x1**2 - 0.00421331967696243*x1*x2**3 + 0.0770714313933922*x1*x2**2 - 0.215977654733002*x1*x2 - 0.681392290927942*x1 + 0.000600569404804807*x2**4 - 0.00978086237435278*x2**3 + 0.0357896164330423*x2**2 - 0.121674409409858*x2 + 0.886626511820445']
[965.9198207882652, 23.65404514218901, '2.72829955384433e-5*x0**2*x1*x2 - 0.00023262956289858*x0**2*x1 + 3.00632137552403e-5*x0**2*x2 + 7.21996510351752e-5*x0**2 + 0.00736029933290511*x0*x1*x2**2 - 0.125572595987532*x0*x1*x2 + 0.535889014700659*x0*x1 - 0.00104904665593723*x0*x2**3 + 0.0136642220611202*x0*x2**2 - 0.00838664365453991*x0*x2 + 0.741836183925367*x0 + 6.14970295763235e-5*x1**3 - 0.0600204937155282*x1**2*x2 + 0.389356252208634*x1**2 - 0.00421331967696243*x1*x2**3 + 0.0770714313933922*x1*x2**2 - 0.215977654733002*x1*x2 - 0.681392290927942*x1 + 0.000600569404804807*x2**4 - 0.00978086237435278*x2**3 + 0.0357896164330423*x2**2 - 0.121674409409858*x2 + 0.886626511820445']
[998.2529146125704, 23.639666252586863, '2.72829955384433e-5*x0**2*x1*x2 - 0.00023262956289858*x0**2*x1 + 3.00632137552403e-5*x0**2*x2 + 7.21996510351752e-5*x0**2 + 1.80347380637521e-5*x0*x1**2 + 0.00736029933290511*x0*x1*x2**2 - 0.125572595987532*x0*x1*x2 + 0.535889014700659*x0*x1 - 0.00104904665593723*x0*x2**3 + 0.0136642220611202*x0*x2**2 - 0.00838664365453991*x0*x2 + 0.741836183925367*x0 + 6.14970295763235e-5*x1**3 - 0.0600204937155282*x1**2*x2 + 0.389356252208634*x1**2 - 0.00421331967696243*x1*x2**3 + 0.0770714313933922*x1*x2**2 - 0.215977654733002*x1*x2 - 0.681392290927942*x1 + 0.000600569404804807*x2**4 - 0.00978086237435278*x2**3 + 0.0357896164330423*x2**2 - 0.121674409409858*x2 + 0.886626511820445']
[1032.153137154247, 23.51963882105246, '2.72829955384433e-5*x0**2*x1*x2 - 0.00023262956289858*x0**2*x1 + 3.00632137552403e-5*x0**2*x2 + 7.21996510351752e-5*x0**2 + 1.80347380637521e-5*x0*x1**2 + 0.00736029933290511*x0*x1*x2**2 - 0.125572595987532*x0*x1*x2 + 0.535889014700659*x0*x1 - 0.00104904665593723*x0*x2**3 + 0.0136642220611202*x0*x2**2 - 0.00838664365453991*x0*x2 + 0.741836183925367*x0 + 6.14970295763235e-5*x1**3 + 1.78131750317296e-5*x1**2*x2**2 - 0.0600204937155282*x1**2*x2 + 0.389356252208634*x1**2 - 0.00421331967696243*x1*x2**3 + 0.0770714313933922*x1*x2**2 - 0.215977654733002*x1*x2 - 0.681392290927942*x1 + 0.000600569404804807*x2**4 - 0.00978086237435278*x2**3 + 0.0357896164330423*x2**2 - 0.121674409409858*x2 + 0.886626511820445']
Checking for brute force +

^M: Command not found.
^M: Command not found.
Trying to solve mysteries with brute force...
^M: Command not found.
...ing to solve results/mystery_world_acos/example2.txt_train
 mystery.datesults/mystery_world_acos/example2.txt_train
/bin/cp: cannot stat 'results/mystery_world_acos/example2.txt_train'$'\r': No such file or directory
^M: Command not found.
timeout: invalid time interval ‘60\rs’
Try 'timeout --help' for more information.
^M: Command not found.
Checking for brute force *

^M: Command not found.
^M: Command not found.
Trying to solve mysteries with brute force...
^M: Command not found.
...ing to solve results/mystery_world_acos/example2.txt_train
 mystery.datesults/mystery_world_acos/example2.txt_train
/bin/cp: cannot stat 'results/mystery_world_acos/example2.txt_train'$'\r': No such file or directory
timeout: invalid time interval ‘60\rs’
Try 'timeout --help' for more information.
Checking polyfit

Complexity  RMSE  Expression
[13.60964047443681, 31.770329997618862, 'x0*x1 + x0 - x1 + 1']
[59.21663995022191, 30.57115402958708, '0.535889014700659*x0*x1 + x0 - x1 + 1']
[249.31526647943755, 28.94369572341426, '0.535889014700659*x0*x1 + 0.741836183925367*x0 + 0.389356252208634*x1**2 - 0.215977654733002*x1*x2 - 0.681392290927942*x1 + 1']
[597.0755011637102, 27.466495540561752, '-0.125572595987532*x0*x1*x2 + 0.535889014700659*x0*x1 + 0.0136642220611202*x0*x2**2 + 0.741836183925367*x0 - 0.0600204937155282*x1**2*x2 + 0.389356252208634*x1**2 + 0.0770714313933922*x1*x2**2 - 0.215977654733002*x1*x2 - 0.681392290927942*x1 - 0.00978086237435278*x2**3 + 0.0357896164330423*x2**2 - 0.121674409409858*x2 + 0.886626511820445']
[636.6848037652464, 27.05335573865928, '-0.125572595987532*x0*x1*x2 + 0.535889014700659*x0*x1 + 0.0136642220611202*x0*x2**2 - 0.00838664365453991*x0*x2 + 0.741836183925367*x0 - 0.0600204937155282*x1**2*x2 + 0.389356252208634*x1**2 + 0.0770714313933922*x1*x2**2 - 0.215977654733002*x1*x2 - 0.681392290927942*x1 - 0.00978086237435278*x2**3 + 0.0357896164330423*x2**2 - 0.121674409409858*x2 + 0.886626511820445']
[795.0447340856714, 23.86627678145459, '0.00736029933290511*x0*x1*x2**2 - 0.125572595987532*x0*x1*x2 + 0.535889014700659*x0*x1 - 0.00104904665593723*x0*x2**3 + 0.0136642220611202*x0*x2**2 - 0.00838664365453991*x0*x2 + 0.741836183925367*x0 - 0.0600204937155282*x1**2*x2 + 0.389356252208634*x1**2 - 0.00421331967696243*x1*x2**3 + 0.0770714313933922*x1*x2**2 - 0.215977654733002*x1*x2 - 0.681392290927942*x1 + 0.000600569404804807*x2**4 - 0.00978086237435278*x2**3 + 0.0357896164330423*x2**2 - 0.121674409409858*x2 + 0.886626511820445']
[965.9198207882652, 23.65404514218901, '2.72829955384433e-5*x0**2*x1*x2 - 0.00023262956289858*x0**2*x1 + 3.00632137552403e-5*x0**2*x2 + 7.21996510351752e-5*x0**2 + 0.00736029933290511*x0*x1*x2**2 - 0.125572595987532*x0*x1*x2 + 0.535889014700659*x0*x1 - 0.00104904665593723*x0*x2**3 + 0.0136642220611202*x0*x2**2 - 0.00838664365453991*x0*x2 + 0.741836183925367*x0 + 6.14970295763235e-5*x1**3 - 0.0600204937155282*x1**2*x2 + 0.389356252208634*x1**2 - 0.00421331967696243*x1*x2**3 + 0.0770714313933922*x1*x2**2 - 0.215977654733002*x1*x2 - 0.681392290927942*x1 + 0.000600569404804807*x2**4 - 0.00978086237435278*x2**3 + 0.0357896164330423*x2**2 - 0.121674409409858*x2 + 0.886626511820445']
[998.2529146125704, 23.639666252586863, '2.72829955384433e-5*x0**2*x1*x2 - 0.00023262956289858*x0**2*x1 + 3.00632137552403e-5*x0**2*x2 + 7.21996510351752e-5*x0**2 + 1.80347380637521e-5*x0*x1**2 + 0.00736029933290511*x0*x1*x2**2 - 0.125572595987532*x0*x1*x2 + 0.535889014700659*x0*x1 - 0.00104904665593723*x0*x2**3 + 0.0136642220611202*x0*x2**2 - 0.00838664365453991*x0*x2 + 0.741836183925367*x0 + 6.14970295763235e-5*x1**3 - 0.0600204937155282*x1**2*x2 + 0.389356252208634*x1**2 - 0.00421331967696243*x1*x2**3 + 0.0770714313933922*x1*x2**2 - 0.215977654733002*x1*x2 - 0.681392290927942*x1 + 0.000600569404804807*x2**4 - 0.00978086237435278*x2**3 + 0.0357896164330423*x2**2 - 0.121674409409858*x2 + 0.886626511820445']
[1032.153137154247, 23.51963882105246, '2.72829955384433e-5*x0**2*x1*x2 - 0.00023262956289858*x0**2*x1 + 3.00632137552403e-5*x0**2*x2 + 7.21996510351752e-5*x0**2 + 1.80347380637521e-5*x0*x1**2 + 0.00736029933290511*x0*x1*x2**2 - 0.125572595987532*x0*x1*x2 + 0.535889014700659*x0*x1 - 0.00104904665593723*x0*x2**3 + 0.0136642220611202*x0*x2**2 - 0.00838664365453991*x0*x2 + 0.741836183925367*x0 + 6.14970295763235e-5*x1**3 + 1.78131750317296e-5*x1**2*x2**2 - 0.0600204937155282*x1**2*x2 + 0.389356252208634*x1**2 - 0.00421331967696243*x1*x2**3 + 0.0770714313933922*x1*x2**2 - 0.215977654733002*x1*x2 - 0.681392290927942*x1 + 0.000600569404804807*x2**4 - 0.00978086237435278*x2**3 + 0.0357896164330423*x2**2 - 0.121674409409858*x2 + 0.886626511820445']
```

**Comment by Betaglutamate** [comment]
So i fixed the above issue by running the .src files through dos2unix.

I was able to solve example file 2 in 2H45 minutes using an intel core i7 9750h. I am running pytorch without cuda acceleration. CPU and ram utilization were between 10-20%.

**Comment by SJ001** [comment]
I am really sorry for my delayed reply! 2H45 mins sounds more or less right. So is everything working now. Can I help in any way?
