### ISSUE TITLE
OSError: results_gen_sym.dat not found.

### ISSUE THREAD

**Issue by mbennun** [SJ001/AI-Feynman#63]
I am trying the example using:
aifeynman.run_aifeynman("./example_data/", "example1.txt", 60, "14ops.txt", polyfit_deg=3, NN_epochs=500)

It runs and then fails with this error:

Checking for generalized symmetry...
identify_decompositions ./example_data/ example1.txt_train
Trying (0, 1)
(1.2643647381029814, (0, 1))
Trying (0, 2)
(3.397227321254669, (0, 2))
Trying (1, 2)
(3.3632891097948683, (1, 2))
mask [ True False  True]
Trying to solve mysteries with brute force...
Trying to solve results/gradients_gen_sym_example1.txt_train
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/aifeynman/S_run_aifeynman.py", line 274, in run_aifeynman
    PA = run_AI_all(pathdir,filename+"_train",BF_try_time,BF_ops_file_type, polyfit_deg, NN_epochs, PA=PA)
  File "/usr/local/lib/python3.9/site-packages/aifeynman/S_run_aifeynman.py", line 156, in run_AI_all
    bf_all_output = np.loadtxt("results_gen_sym.dat", dtype="str")
  File "/usr/local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 1067, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/usr/local/lib/python3.9/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/usr/local/lib/python3.9/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise IOError("%s not found." % path)
OSError: results_gen_sym.dat not found.

**Comment by kvyaswanth** [comment]
results_gen_sym.dat was to be generated  by this file "feynman_sr_mdl5"

I suggest checking if the file is executable, or try using print statement [here](https://github.com/SJ001/AI-Feynman/blob/a05bc4a5be23d6eb3e1d0b2f7eb1ab5b78a920ad/aifeynman/S_brute_force_gen_sym.py#L62) to check if the above mentioned code is running

**Comment by toontran** [comment]
Apparently if you want to use AI Feynman 2.0, it's better to use a historical version of this repo, according to [this article](https://towardsdatascience.com/ai-feynman-2-0-learning-regression-equations-from-data-3232151bd929)

**Comment by Rafail-Karkanis** [comment]
I am getting the same error.
@kvyaswanth This returns a [Errno 2] No such file or directory: 'feynman_sr_mdl5'
@toontran I tried to use dcshapiro's fork, but it returns another error upon executing the example.py
Is there any commit hash that actually works?

**Comment by alen-1998** [comment]
安装不正确导致这个命令出错'feynman_sr_mdl5 = aifeynman._symbolic_regress_mdl5:go'。
conda环境可以试下这个方法，需要修改setup.py部分内容
```bash
conda create -n feynman python=3.7 #(numpy 1.16.0 would require python >=3.7,<3.8.0a0 )
conda activate feyn
conda install numpy==1.16
#The symbol `PyDataType_SET_ELSIZE` has been removed in newer versions of NumPy.
# If the NumPy version is higher than 1.16, it is recommended to downgrade to 
# version 1.16 to ensure compatibility.
conda install scikit-learn
conda install pytorch==1.1.0 torchvision==0.3.0 -c pytorch
conda insatll matplotlib scipy pandas sortedcontainers
sudo apt install gfortran
git clone https://github.com/SJ001/AI-Feynman.git
pip install .  
```
测试一下brute_force是否正常
```python
from aifeynman.S_brute_force import brute_force
brute_force("./AI-feynman/example_data/","example1.txt",30,"14ops.txt")
```
